SF Bug Tracker #128, Creator: Nick Leverton redefining strndup causes "error: expected identifier or '('before '__extension__'"
Fix redefinition of strnlen and strndup

These are available when HAVE_STRNDUP and HAVE_STRNLEN are defined, but
libupnp provides an extern prototype anyway.  Recent versions of glibc
define this prototype differently, causing the following compile error:

	src/api/UpnpString.c:47:15: error: expected identifier or '(' before  '__extension__'
		extern char *strndup(__const char *__string, size_t __n);

Signed-off-by: Marcelo Roberto Jimenez <mroberto@users.sourceforge.net>